branches:
  - master
plugins:
  - - @semantic-release/commit-analyzer
    - preset: angular
      parserOpts:
        noteKeywords:
          - 'BREAKING CHANGE'
          - 'BREAKING CHANGES'
          - 'BREAKING'
  - - @semantic-release/exec
    - successCmd: 'echo "TAG_STATUS=SUCCESS" >> $GITHUB_OUTPUT && echo "SEM_NEXT_VERSION=${nextRelease.version}" >> $GITHUB_OUTPUT && echo "SEM_LAST_VERSION=${lastRelease.version}" >> $GITHUB_OUTPUT'
      failCmd: 'echo "TAG_STATUS=FAIL" >> $GITHUB_OUTPUT'
