branches:
  - name: main

tagFormat: ${version}-project-a

plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
      parserOpts:
        noteKeywords:
          - 'BREAKING CHANGE'
          - 'BREAKING CHANGES'
          - 'BREAKING'
  - - '@semantic-release/exec'
    - successCmd: 'echo "status=SUCCESS" >> $GITHUB_OUTPUT && echo "version=${nextRelease.version}" >> $GITHUB_OUTPUT && echo "last_version=${lastRelease.version}" >> $GITHUB_OUTPUT'
      failCmd: 'echo "status=FAIL" >> $GITHUB_OUTPUT'
