name: Bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

permissions:
  checks: write
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release:
    name: Bump and create PR
    runs-on: ubuntu-latest

    steps:
      - name: Print dispatch event payload
        run: |
          echo "version: ${{ inputs.version }}"

      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Create and checkout branch
        run: git checkout -b chore/bump-components-${{ inputs.version }}

      - name: Commit and push changes
        run: |
          echo "a" >> test.txt
          git config --global user.email "mnagy112@gmail.com"
          git config --global user.name "Test Bot"
          git add test.txt
          git commit -m "feat: bump"
          git push --set-upstream origin chore/bump-components-${{ inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_SYSTEM_USER }}

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;

            const result = await github.rest.pulls.create({
              title: 'feat: bump components (${{ inputs.version }})',
              owner,
              repo,
              head: 'chore/bump-components-${{ inputs.version }}',
              base: 'master',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            
            console.log(result);

            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['bump']
            });

            github.rest.checks.create({
              owner,
              repo,
              name: 'call-tests',
              head_sha: result.data.head.sha,
            });
