name: Cache between jobs

on:
  push:
#    branches:
#      - unused

permissions:
  id-token: write
  contents: read

jobs:
  sample:
    name: Sample
    runs-on: ubuntu-latest
    outputs:
      output_claim-handler: ${{ steps.gen_output.outputs.output_claim-handler }}
      output_common: ${{ steps.gen_output.outputs.output_common }}
      output_coordinator: ${{ steps.gen_output.outputs.output_coordinator }}
    strategy:
      fail-fast: false
      matrix:
        test-suite:
          - claim-handler
          - common
          - coordinator

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install
        if: matrix.test-suite == 'claim-handler'
        run: exit 1

      - name: Install
        if: matrix.test-suite != 'claim-handler'
        run: echo "Hello"

      - name: Generate report for suites
        id: report
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { getSuitesReport } = await import('${{ github.workspace }}/report.mjs')
            return getSuitesReport();

      - name: Generate output
        id: gen_output
        if: always()
        run: |
          echo "output_${{ matrix.test-suite }}='${{steps.report.outputs.result}}'" >> "$GITHUB_OUTPUT"

  second:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - sample
    steps:
      - run: echo '${{ toJSON(needs.sample.outputs) }}'
