name: Create prod release

on:
  repository_dispatch:
    types:
      - create-prod-release

permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: Create release from version
    runs-on: ubuntu-latest

    steps:
      - name: Print dispatch event payload
        run: |
          echo "version: ${{ github.event.client_payload.version }}"

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            const { repo, owner } = context.repo;

            await github.rest.repos.createRelease({
              owner,
              repo,
              draft: true,
              name: '${{ github.event.client_payload.version }}',
              tag_name: '${{ github.event.client_payload.version }}',
              generate_release_notes: true,
            });
