name: Create prod release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: Create release from version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install -D git-raw-commits conventional-commits-parser conventional-changelog-writer conventional-changelog-conventionalcommits

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            const { default: doStuff } = await import('${{ github.workspace }}/sample.mjs')

            await doStuff(github, context)

#            await github.rest.repos.createRelease({
#              owner,
#              repo,
#              name: 'v1.19.0',
#              tag_name: 'v1.19.0',
#              body: commits.join('\n')
#            });
