name: Create prod release

on:
  repository_dispatch:
    types:
      - create-prod-release

permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: Create release from version
    runs-on: ubuntu-latest

    steps:
      - name: Print dispatch event payload
        run: |
          echo "version: ${{ github.event.client_payload.version }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
