name: Dispatch test

on:
  push:
    branches:
      - test

permissions:
  id-token: write
  contents: read

jobs:
  prepare-versions:
    name: Dispatch test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger
        uses: mnagy-g/actiontest@master
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: dispatchtest
          event-type: test-action
          check-interval: 5s
          timeout: 20s
          client-payload: '{ "version": "test" }'
