name: release
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write

jobs:
  get:
    name: Get Release
    runs-on: ubuntu-latest

#    outputs:
#      TAG_STATUS: ${{ steps.tag-commit.outputs.TAG_STATUS }}
#      SEM_NEXT_VERSION: ${{ steps.tag-commit.outputs.SEM_NEXT_VERSION }}
#      SEM_LAST_VERSION: ${{ steps.tag-commit.outputs.SEM_LAST_VERSION }}

    steps:
      - name: Get release
        id: get-release
        uses: actions/github-script@v6
        with:
          script: |
            const releases = github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            
            return {
              id: releases[0].id
              tag: releases[0].tag_name
            }

      - name: Get result
        run: echo "${{steps.get-release.outputs.result}}"

      - name: Get result
        run: |
          echo "${{steps.get-release.outputs.result.id}}"
          echo "${{steps.get-release.outputs.result.tag}}"
