name: Hello world

on:
  repository_dispatch:
    types:
      - test

permissions:
  id-token: write
  contents: read

jobs:
  prepare-versions:
    name: Hello world
    runs-on: ubuntu-latest

    steps:
      - name: Print dispatch event payload
        run: |
          echo "version: ${{ github.event.client_payload.version }}"

      - name: Hello world
        run: echo "Hello world"
