name: Manual

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!master'

permissions:
  id-token: write
  contents: read

jobs:
  manual:
    name: Execute tests
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[deploy]') || (github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/master')

    steps:
      - name: Print hello world
        run: |
          echo "Hello world"
