name: Pull request checks

on:
  pull_request:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  call-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello world
        run: |
          echo "Hello world"
