name: Release TEST

on:
  workflow_call:
    inputs:
      env:
        description: Env
        required: true
        type: string
      version:
        description: Env
        required: false
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  test:
    name: Test ENV
    runs-on: ubuntu-latest

    steps:
      - name: Test Condition with version
        if: ${{ inputs.version != '' }}
        run: |
          echo "Env: ${{ inputs.version || github.sha }}"

      - name: Test Condition without version
        if: ${{ inputs.version == '' }}
        run: |
          echo "Env: ${{ inputs.version || github.sha }}"

      - name: Test
        run: |
          echo "Repo name: ${{ github.event.repository.name }}"

      - name: Test ENV
        uses: actions/github-script@v7
        with:
          script: |
            const inputs = ${{ toJSON(inputs) }};
            console.log(inputs.env.split('\n').map(e => e.split('=')).reduce((acc, [k, v]) => ({ ...acc, [k]: v }), {}));

