name: Release TEST

on:
  workflow_call:
    inputs:
      env:
        description: Env
        required: true
        type: string
      version:
        description: Env
        required: false
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  test:
    name: Test ENV
    runs-on: ubuntu-latest

    steps:
      - name: Test Condition with version
        if: ${{ inputs.version != '' }}
        run: |
          echo "Env: ${{ inputs.version || github.sha }}"

      - name: Test Condition without version
        if: ${{ inputs.version == '' }}
        run: |
          echo "Env: ${{ inputs.version || github.sha }}"

      - name: Test
        run: |
          echo "Repo name: ${{ github.event.repository.name }}"

      - name: Test ENV
        uses: actions/github-script@v7
        with:
          script: |
            const inputs = JSON.parse(${{ toJSON(inputs.env) }});
            
            console.log(inputs);

#            for (const [key, value] of Object.entries(JSON.parse(inputs.env))) {
#              console.log(`${key}: ${value}`);
#              core.exportVariable(key, value);
#            }

      - name: Test
        run: |
          echo "VITE_APP_NAME: ${{ env.VITE_APP_NAME }}"
          echo "VITE_APP_VERSION: ${{ env.VITE_APP_VERSION }}"
