name: VV Release [TEST]

on:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: read

jobs:
  prepare-versions:
    name: Prepare versions
    runs-on: ubuntu-latest

    steps:
      - name: Get release tag
        id: get-tag
        run: echo "RELEASE_TAG=${ GITHUB_REF#refs/tags/ }" >> $GITHUB_OUTPUT

      - name: Print tag
        run: echo "${{ steps.get-tag.outputs.RELEASE_TAG }}"
