name: Release TEST

on:
  push:
    branches:
      - disabled

permissions:
  id-token: write
  contents: write

jobs:
  tag-commit:
    name: Tag commit
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip:ci]') }}

    outputs:
      TAG_STATUS: ${{ steps.tag-commit.outputs.TAG_STATUS }}
      SEM_NEXT_VERSION: ${{ steps.tag-commit.outputs.SEM_NEXT_VERSION }}
      SEM_LAST_VERSION: ${{ steps.tag-commit.outputs.SEM_LAST_VERSION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
#          scope: 'ToDo'

      - name: Install
        run: npm install -D semantic-release @semantic-release/exec conventional-changelog-conventionalcommits
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_SYSTEM_USER }}

      - name: Tag commit
        id: tag-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Print result
        run: |
          echo "STATUS: ${{ steps.tag-commit.outputs.TAG_STATUS }}"
          echo "NEXT VERSION: ${{ steps.tag-commit.outputs.SEM_NEXT_VERSION }}"
          echo "LAST VERSION: ${{ steps.tag-commit.outputs.SEM_LAST_VERSION }}"

  execute-release:
    name: Execute release
    runs-on: ubuntu-latest
    needs: tag-commit
    if: ${{ needs.tag-commit.outputs.TAG_STATUS == 'SUCCESS' }}

    steps:
      - name: Execute release
        id: versions
        run: |
          echo "Hello I am executing release to TEST"

  trigger-prod-release:
    name: Trigger prod release
    runs-on: ubuntu-latest
    needs:
      - tag-commit
      - execute-release

    steps:
      - name: Trigger prod release
        uses: mnagy-g/actiontest@master
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: semtest
          event-type: create-prod-release
          client-payload: '{ "version": "v${{ needs.tag-commit.outputs.SEM_NEXT_VERSION }}" }'

  rollback:
    name: Rollback
    runs-on: ubuntu-latest
    needs:
      - tag-commit
      - execute-release
    if: failure()

    steps:
      - name: Delete tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/v${{ needs.tag-commit.outputs.SEM_NEXT_VERSION }}',
            })
