name: release
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip:ci]')"
    name: Create Release
    runs-on: ubuntu-latest

    outputs:
      TAG_STATUS: ${{ steps.tag-commit.outputs.TAG_STATUS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_SYSTEM_USER }}

      - name: Tag commit
        id: tag-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release

      - name: Print result
        run: |
          echo ${{ steps.tag-commit.outputs.TAG_STATUS }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.TAG_STATUS == 'SUCCESS' }}

    outputs:
      TAG_STATUS: ${{ steps.tag-commit.outputs.TAG_STATUS }}

    steps:
      - name: Echo
        id: versions
        run: |
          echo "Hello World!"
