name: Tests and Lints

on:
  workflow_call:
    inputs:
      ref:
        description: 'Ref to trigger tests on'
        required: false
        type: string

jobs:
  test:
    name: Execute tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Print test content
        run: |
          cat test.txt

      - name: Print hello world
        run: |
          echo "Hello world"

      - name: Error
        run: |
          exit 1
