name: Release TEST

on:
  push:
#    branches:
#      - unused

permissions:
  id-token: write
  contents: write

jobs:
  test:
    name: Test ENV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code for building
        uses: actions/checkout@v4

      - name: Trigger prod release
        uses: mnagy-g/actiontest@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: semtest
          event-type: test-github-context
          client-payload: '{ "version": "v123" }'
