name: Release TEST

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  test-without-version:
    name: Without version
    uses: ./.github/workflows/r_test-env.yml
    needs:
      - env-setup
    with:
      env: |
        VITE_APP_NAME="app name"
        VITE_APP_VERSION="v1.0.0"
    secrets: inherit

  test-with-version:
    name: With version
    uses: ./.github/workflows/r_test-env.yml
    needs:
      - env-setup
    with:
      version: 1.2.3
      env: |
        VITE_APP_NAME="app name"
        VITE_APP_VERSION="v1.0.0"
    secrets: inherit
